apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: server-allow-ingress
  namespace: customer-insights
  labels:
    app: server
spec:
  podSelector:
    matchLabels:
      app: server
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: app-routing-system
